name:                dynamic-progrmamming-ch4
version:             0.1.0.0
github:              "Daedauls359/dynamic-progrmamming-ch4"
license:             BSD3
author:              "Kevin Bradner"
maintainer:          "kbradner112@gmail.com"
copyright:           "none"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Daedauls359/dynamic-progrmamming-ch4#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers
  - unordered-containers
  - hashable
  - deepseq

executables:
  jacks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-progrmamming-ch4
    - containers
    - hashable

tests:
  dynamic-progrmamming-ch4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynamic-progrmamming-ch4
